adding theatre controller
sarithsajeev/BookYourShow pull request #16
Opened 2022-01-04 04:19 UTC by RashmiNayak-S

2022-01-05 06:57 UTC, basilin requested changes

2022-01-05 06:57 UTC, basilin commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +            //throw new Exception("Exception occurred!");
remove

2022-01-05 06:57 UTC, basilin commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +
remove unwanted spaces

2022-01-05 06:57 UTC, basilin commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +        //[Route("updatetheatre")]
?

2022-01-06 06:40 UTC, RashmiNayak-S commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +            //throw new Exception("Exception occurred!");
resolved

2022-01-06 06:40 UTC, RashmiNayak-S commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +
resolved

2022-01-06 06:40 UTC, RashmiNayak-S commented on src/BookYourShow.Api/Controllers/TheatreController.cs
> +        //[Route("updatetheatre")]
resolved

2022-01-07 05:37 UTC, merged